//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Ranking { get; set; }
        public string Number { get; set; }
        public bool ManualInput { get; set; }
    }
}
