//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentTemp
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string ParentCode { get; set; }
        public System.Guid DivisionId { get; set; }
        public string DivisionCode { get; set; }
        public Nullable<System.Guid> ChiefId { get; set; }
        public Nullable<System.Guid> ChiefPersonId { get; set; }
        public string Department { get; set; }
        public string Ranking { get; set; }
        public string Number { get; set; }
        public System.DateTime ValidationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
