//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.DepartmentStates = new HashSet<DepartmentState>();
            this.DivisionPhoneCodes = new HashSet<DivisionPhoneCode>();
            this.DivisionPhoneCodes1 = new HashSet<DivisionPhoneCode>();
            this.DivisionStates = new HashSet<DivisionState>();
            this.DivisionStates1 = new HashSet<DivisionState>();
            this.Locations = new HashSet<Location>();
            this.TerritoryStates = new HashSet<TerritoryState>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string Ranking { get; set; }
        public bool Essential { get; set; }
    
        public virtual ICollection<DepartmentState> DepartmentStates { get; set; }
        public virtual ICollection<DivisionPhoneCode> DivisionPhoneCodes { get; set; }
        public virtual ICollection<DivisionPhoneCode> DivisionPhoneCodes1 { get; set; }
        public virtual ICollection<DivisionState> DivisionStates { get; set; }
        public virtual ICollection<DivisionState> DivisionStates1 { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<TerritoryState> TerritoryStates { get; set; }
    }
}
