//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionPhoneCode
    {
        public System.Guid Id { get; set; }
        public System.Guid DivisionFromId { get; set; }
        public System.Guid DivisionToId { get; set; }
        public string IntPhoneCode { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Division Division1 { get; set; }
    }
}
