//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public System.Guid PersonId { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string EMail { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountControl { get; set; }
        public Nullable<bool> Updated { get; set; }
        public bool ManualInput { get; set; }
        public byte[] Photo { get; set; }
        public System.DateTime PhotoDate { get; set; }
        public string PhotoFile { get; set; }
        public bool PhotoAllowed { get; set; }
        public bool PhotoUpdated { get; set; }
        public bool PhotoManualInput { get; set; }
        public Nullable<int> AdState { get; set; }
        public Nullable<bool> isAdministrator { get; set; }
    }
}
