//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DepartmentStates = new HashSet<DepartmentState>();
            this.EmployeePlaces = new HashSet<EmployeePlace>();
            this.Favorites = new HashSet<Favorite>();
            this.Favorites1 = new HashSet<Favorite>();
            this.SpecificStaffs = new HashSet<SpecificStaff>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public System.Guid PersonId { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string ITN { get; set; }
        public string SeriesPas { get; set; }
        public string NumberPas { get; set; }
        public string PasDepart { get; set; }
        public Nullable<System.DateTime> PasIssue { get; set; }
        public string EMail { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountControl { get; set; }
        public Nullable<bool> Updated { get; set; }
        public bool ManualInput { get; set; }
        public System.DateTime PhotoDate { get; set; }
        public string PhotoFile { get; set; }
        public bool PhotoAllowed { get; set; }
        public bool PhotoUpdated { get; set; }
        public bool PhotoManualInput { get; set; }
        public Nullable<int> AdState { get; set; }
        public Nullable<bool> isAdministrator { get; set; }
        public string RossetiCode { get; set; }
        public byte[] Photo { get; set; }
        public int Position { get; set; }
        public Nullable<bool> IsMemberOfHeadquarter { get; set; }
    
        public virtual ICollection<DepartmentState> DepartmentStates { get; set; }
        public virtual ICollection<EmployeePlace> EmployeePlaces { get; set; }
        public virtual ICollection<Favorite> Favorites { get; set; }
        public virtual ICollection<Favorite> Favorites1 { get; set; }
        public virtual ICollection<SpecificStaff> SpecificStaffs { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
