//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExecutionLog
    {
        public System.Guid Id { get; set; }
        public string DivisionCode { get; set; }
        public int Type { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Description { get; set; }
        public int Code { get; set; }
    }
}
