//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.EmployeePlaces = new HashSet<EmployeePlace>();
            this.SpecificStaffPlaces = new HashSet<SpecificStaffPlace>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DivisionId { get; set; }
        public System.Guid LocalityId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public string Street { get; set; }
        public string Edifice { get; set; }
        public string Building { get; set; }
        public Nullable<System.Guid> PhoneZoneId { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual ICollection<EmployeePlace> EmployeePlaces { get; set; }
        public virtual Locality Locality { get; set; }
        public virtual PhoneZoneInt PhoneZoneInt { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual ICollection<SpecificStaffPlace> SpecificStaffPlaces { get; set; }
    }
}
