//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public System.Guid Id { get; set; }
        public System.Guid DivisionId { get; set; }
        public System.Guid LocalityId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public string Street { get; set; }
        public string Edifice { get; set; }
        public string Building { get; set; }
        public Nullable<System.Guid> PhoneZoneId { get; set; }
    }
}
