//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneMatrixInt
    {
        public System.Guid Id { get; set; }
        public System.Guid FromId { get; set; }
        public System.Guid ToId { get; set; }
        public string PhoneCode { get; set; }
    }
}
