//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneZoneInt
    {
        public PhoneZoneInt()
        {
            this.Locations = new HashSet<Location>();
            this.PhoneMatrixInts = new HashSet<PhoneMatrixInt>();
            this.PhoneMatrixInts1 = new HashSet<PhoneMatrixInt>();
        }
    
        public System.Guid Id { get; set; }
        public string Zone { get; set; }
    
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<PhoneMatrixInt> PhoneMatrixInts { get; set; }
        public virtual ICollection<PhoneMatrixInt> PhoneMatrixInts1 { get; set; }
    }
}
