//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.PositionStates = new HashSet<PositionState>();
            this.Staffs = new HashSet<Staff>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public System.Guid TitleId { get; set; }
        public string TitleCode { get; set; }
        public System.Guid DepartmentId { get; set; }
        public string DepartmentCode { get; set; }
        public string Ranking { get; set; }
        public bool ManualInput { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<PositionState> PositionStates { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
