//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position1S
    {
        public string Code { get; set; }
        public string TitleCode { get; set; }
        public string DivisionCode { get; set; }
        public string DepartmentCode { get; set; }
        public string Title { get; set; }
        public string Ranking { get; set; }
        public System.DateTime ValidationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
