//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificStaff
    {
        public SpecificStaff()
        {
            this.SpecificStaffPlaces = new HashSet<SpecificStaffPlace>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid DepartmentId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string Position { get; set; }
        public string Ranking { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<SpecificStaffPlace> SpecificStaffPlaces { get; set; }
    }
}
