//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTemp
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid DepartmentId { get; set; }
        public string DepartmentCode { get; set; }
        public System.Guid PositionId { get; set; }
        public string PositionCode { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string ITN { get; set; }
        public string SeriesPas { get; set; }
        public string NumberPas { get; set; }
        public string PasDepart { get; set; }
        public Nullable<System.DateTime> PasIssue { get; set; }
        public byte[] Photo { get; set; }
        public System.DateTime PhotoDate { get; set; }
        public string PhotoFile { get; set; }
        public bool PhotoAllowed { get; set; }
        public System.DateTime ValidationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
