//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSS.Server.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public System.Guid Id { get; set; }
        public System.Guid DepartmentId { get; set; }
        public Nullable<System.Guid> PositionId { get; set; }
        public Nullable<System.DateTime> HolidayStartDate { get; set; }
        public Nullable<System.DateTime> HolidayEndDate { get; set; }
        public System.DateTime ValidationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
    }
}
